### ISSUE TITLE
Keeper Passives

### ISSUE THREAD

**Issue by sillypears** [Zamiell/isaac-racing-mods#3]
I just realized you wrote that you cannot give the 3 passives to Keeper, however in my "testing" mod I made I am able to start Keeper with at least 1 passive (Spidermod, #403). I know the active issue as the nickle overwrites anything in that slot. Strictly talking about passives. Just curious if I'm missing something or if it is possible.

**Comment by Zamiell** [comment]
fixed, will be included in the next version
