### ISSUE TITLE
Add buttons with rulesets

### ISSUE THREAD

**Issue by Birdie0** [Zamiell/isaac-racing-mods#4]
I have a good idea: add buttons to menu that call popups or open browser with ruleset page. It can be useful for newbies and refresh knowledge for veterans.
Examples of button placing:

![2016-10-01 00_05_06-jud6s mod v1 32](https://cloud.githubusercontent.com/assets/7945905/19006965/171f9856-876b-11e6-9961-26962c644e08.png)

![2016-10-01 00_05_21-instant start mod v3 5 0](https://cloud.githubusercontent.com/assets/7945905/19006966/17208b8a-876b-11e6-9403-7527a6fed7d4.png)

![2016-10-01 00_05_32-diversity mod v3 5 0](https://cloud.githubusercontent.com/assets/7945905/19006964/171f694e-876b-11e6-854e-e1c7d7cfd7e9.png)

**Comment by Zamiell** [comment]
Done.
