### ISSUE TITLE
Update reset path to isaac-ng.exe

### ISSUE THREAD

**Issue by Birdie0** [Zamiell/isaac-racing-mods#6]
After updating to new version my path to isaac-ng.exe was reset and it not in first time.

**Comment by Zamiell** [comment]
This is intended - it will reset whenever the "mod_updater_version" value changes in the "options.ini" file. (https://github.com/Zamiell/isaac-racing-mods/blob/master/options.ini)

This means that it does a full patch. I could save the value of the resources directory when it does a full patch, but I might want to change the variable name at some point, and then the patching itself would break, so I don't really want to do this, as it kills true patchability.
